import Head from 'next/head'
import styles from '../styles/Home.module.css'

const jsLibraries = [
  {
    name: 'React',
    url: 'https://reactjs.org/',
    description: 'A JavaScript library for building user interfaces.'
  },
  {
    name: 'React Router',
    url: 'https://reacttraining.com/react-router/',
    description: 'A React Router library for easily building single-page apps.'
  },
  {
    name: 'Next.js',
    url: 'https://nextjs.org/',
    description: 'A React Framework for server-rendered applications.'
  },
  {
    name: 'Express',
    url: 'https://expressjs.com/',
    description: 'A minimal and flexible Node.js web application framework.'
  },
  {
    name: 'MongoDB',
    url: 'https://www.mongodb.com/',
    description: 'An open-source, cross-platform document-oriented database.'
  }
];


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Get Mah Data</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>JS Libraries</h1>
        <div id="jsLibraries" className={styles.card}>
          {jsLibraries.map(library => (
            <div key={library.name} className={styles.library}>
              <a href={library.url}>{library.name}</a>
              <p>{library.description}</p>
            </div>
          ))}
        </div>
      </main>
    </div>
  )
}
